name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 监听 master 分支的推送
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy to gh-pages
    runs-on: ubuntu-latest

    # 只在推送到 master 分支时部署（不在 PR 时部署）
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，用于 git 信息

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: miusing
          USE_SSH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 使用 Docusaurus 内置的部署命令
          # 这会自动构建并推送到 gh-pages 分支
          npm run deploy
